name: fenics
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - attr=2.5.1=h166bdaf_1
  - binutils_impl_linux-64=2.43=h4bf12b8_2
  - binutils_linux-64=2.43=h4852527_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - eigen=3.4.0=h00ab1b0_0
  - fenics=2019.1.0=hcaacaa7_49
  - fenics-dijitso=2019.1.0=pyhd8ed1ab_39
  - fenics-dolfin=2019.1.0=py39hcc40d10_49
  - fenics-ffc=2019.1.0=pyhd8ed1ab_40
  - fenics-fiat=2019.1.0=pyhd8ed1ab_39
  - fenics-libdolfin=2019.1.0=h0c94697_49
  - fenics-ufl=2019.1.0=py39hf3d152e_38
  - fftw=3.3.10=mpi_mpich_hbcf76dd_10
  - gcc=12.4.0=h236703b_1
  - gcc_impl_linux-64=12.4.0=hb2e57f8_1
  - gcc_linux-64=12.4.0=h6b7512a_7
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py39h7196dd7_3
  - gxx=12.4.0=h236703b_1
  - gxx_impl_linux-64=12.4.0=h613a52c_1
  - gxx_linux-64=12.4.0=h8489865_7
  - hdf5=1.14.3=mpi_mpich_h7f58efa_9
  - hypre=2.31.0=mpi_mpich_hd1da18f_1
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libaec=1.1.3=h59595ed_0
  - libamd=3.3.3=ss783_h889e182
  - libblas=3.9.0=28_h59b9bed_openblas
  - libboost=1.84.0=h6c02f8c_7
  - libboost-headers=1.87.0=ha770c72_1
  - libbtf=2.3.2=ss783_h2377355
  - libcamd=3.3.3=ss783_h2377355
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=28_he106b2a_openblas
  - libccolamd=3.3.4=ss783_h2377355
  - libcholmod=5.3.0=ss783_h3fa60b6
  - libcolamd=3.3.4=ss783_h2377355
  - libcurl=8.11.1=h332b0f4_0
  - libcxsparse=4.4.1=ss783_h2377355
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libfabric=2.0.0=ha770c72_1
  - libfabric1=2.0.0=h14e6f36_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=12.4.0=ha4f9413_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.51=hbd13f7d_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libklu=2.3.5=ss783_hfbdfdfc
  - liblapack=3.9.0=28_h7ac8fdf_openblas
  - libldl=3.3.2=ss783_h2377355
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libparu=1.0.0=ss783_h8814b27
  - libptscotch=7.0.4=h2376d02_5
  - librbio=4.3.4=ss783_h2377355
  - libsanitizer=12.4.0=h46f95d5_1
  - libscotch=7.0.4=h3055ed5_5
  - libspex=3.2.1=ss783_h5a7e440
  - libspqr=4.3.4=ss783_hae1ff0d
  - libsqlite=3.48.0=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=12.4.0=ha4f9413_101
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsuitesparseconfig=7.8.3=ss783_h83006af
  - libsystemd0=257.2=h3dc2cb9_0
  - libudev1=257.2=h9a4d06a_0
  - libumfpack=6.3.5=ss783_hd4f9ce1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h8d12d68_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - metis=5.1.0=hd0bcaf9_1007
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0.1=mpich
  - mpi4py=4.0.2=py39hbe247c9_0
  - mpich=4.2.3=h1a8bee6_104
  - mpmath=1.3.0=pyhd8ed1ab_1
  - mumps-include=5.7.3=ha770c72_0
  - mumps-mpi=5.7.3=hd6ed86c_0
  - ncurses=6.5=h2d0b736_3
  - numpy=1.26.4=py39h474f0d3_0
  - openssl=3.5.1=h7b32b05_0
  - parmetis=4.0.3=hc7bef4e_1007
  - petsc=3.21.5=real_hbe534a9_101
  - petsc4py=3.21.5=py39h2e169e2_1
  - pip=25.0=pyh8b19718_0
  - pkg-config=0.29.2=h4bc722e_1009
  - pkgconfig=1.5.5=pyhd8ed1ab_5
  - pybind11=2.13.4=py39hedd12f3_0
  - pybind11-global=2.13.4=py39hedd12f3_0
  - python=3.9.21=h9c0c6dc_1_cpython
  - python_abi=3.9=5_cp39
  - rdma-core=55.0=h5888daf_0
  - readline=8.2=h8228510_1
  - scalapack=2.2.0=h7e29ba8_4
  - setuptools=75.8.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - slepc=3.21.2=real_h00a54ed_300
  - slepc4py=3.21.2=py39h799f38d_0
  - suitesparse=7.8.3=ss783_h36e971b
  - superlu=7.0.0=h832b8c9_1
  - superlu_dist=9.1.0=h0804ebd_0
  - sympy=1.13.3=pypyh2585a3b_103
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h4845f30_101
  - ucx=1.18.0=hfd9a62f_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.55.8
      - importlib-resources==6.5.2
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - scipy==1.13.1
      - tzdata==2025.1
      - zipp==3.21.0
prefix: /home/kmuly/anaconda3-linux/envs/fenics
